### ISSUE TITLE
Error when trying to connect with 4096 bit rsa key

### ISSUE THREAD

**Issue by redmoses** [Finanzchef24-GmbH/tunnel-ssh#31]
Hi I'm trying to connect using your sample code. But I'm using a 4096 bit rsa key (openssh) and I'm getting the following error - 

Error: Cannot parse privateKey: Unsupported key format

`
Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (~/sshtunnel/node_modules/ssh2/lib/client.js:146:13)
    at start (~/sshtunnel/node_modules/tunnel-ssh/lib/tunnel.js:36:14)
    at Client.client.createStream (~/sshtunnel/node_modules/tunnel-ssh/lib/tunnel.js:64:12)
    at Server.<anonymous> (~/sshtunnel/node_modules/tunnel-ssh/lib/tunnel.js:148:12)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at doNTCallback1 (node.js:430:9)
    at process._tickCallback (node.js:352:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
`

Thanks in advance for your help.

**Comment by redmoses** [comment]
I was passing the file path the 'privateKey' parameter. Once I passed the file content the error went away :)
